<a href="https://colab.research.google.com/github/sajedeh-S/numpy-exercises/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
arange_array = np.arange(0, 10, 2)  # 0 to 10, step of 2
linspace_array = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print("Arange:", arange_array)
print("Linspace:", linspace_array)


Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)    # (rows, columns)
print("Size:", arr.size)      # Total number of elements
print("Dtype:", arr.dtype)    # Data type of elements
print("Ndim:", arr.ndim)      # Number of dimensions


Shape: (2, 3)
Size: 6
Dtype: int64
Ndim: 2


In [ ]:
import numpy as np

#arr = np.array([1, 2, 3, 4, 5, 6])
r1 = arr.reshape(6)
print("Original:\n", arr)
print("Reshaped:\n", r1)
print(arr.reshape((6,)).T)

print(arr.reshape((6,)))
print(arr.reshape((1,6)))
print(arr.reshape((6,1)))

print(arr.reshape((3,2)))

print(arr.T)

print(arr.reshape(-1))

Original:
 [[1 2 3]
 [4 5 6]]
Reshaped:
 [1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


In [ ]:

arr = np.array([[1, 2], [3, 4]])
transposed = arr.T
print(arr)
print("Transposed:\n", transposed)


[[1 2]
 [3 4]]
Transposed:
 [[1 3]
 [2 4]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print("Addition:", arr1 + arr2)

# Subtraction
print("Subtraction:", arr1 - arr2)

# Multiplication
print("Multiplication:", arr1 * arr2)

# Division
print("Division:", arr1 / arr2)


arr = np.array([1, 2, 3])
print("Multiply by 2:", arr * 2)
print("Add 5:", arr + 5)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Multiply by 2: [2 4 6]
Add 5: [6 7 8]


##Broadcasting
NumPy automatically "stretches" smaller arrays to perform operations with larger ones (as long as they are compatible).

In [ ]:
arr = np.array([1, 2, 3])

matrix = np.array([[100], [200], [300]])

# Broadcasting: Adds [1, 2, 3] to each row of the matrix
result = matrix + arr
print("Broadcasting Result:\n", result)

arr = np.array([1])
result = matrix + arr
print("Broadcasting Result:\n", result)

Broadcasting Result:
 [[101 102 103]
 [201 202 203]
 [301 302 303]]
Broadcasting Result:
 [[101]
 [201]
 [301]]


##Aggregate Functions
Aggregate functions compute a single value from all elements of an array.



In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))


Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0


Aggregates Along an Axis


For multidimensional arrays, you can specify an axis:


In [ ]:
matrix = np.array([[[1], [2], [3]], [[4], [5], [6]]])
print(matrix)
print("Sum (columns):", np.sum(matrix, axis=0))  # Sum along columns
print("Sum (rows):", np.sum(matrix, axis=1))    # Sum along rows

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
Sum (columns): [[5]
 [7]
 [9]]
Sum (rows): [[ 6]
 [15]]


In [ ]:
arr = np.array([0, 1, 2, 3])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr + 1))  # Adding 1 to avoid log(0)
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))


Square root: [0.         1.         1.41421356 1.73205081]
Exponential: [ 1.          2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229 1.38629436]
Sine: [0.         0.84147098 0.90929743 0.14112001]
Cosine: [ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [ ]:
arr = np.array([10, 20, 30])

print("Greater than 15:", arr > 15)
print("Greater than 15:", arr[arr > 15])

print("Equal to 20:", arr == 20)


Greater than 15: [False  True  True]
Greater than 15: [20 30]
Equal to 20: [False  True False]


In [ ]:
print("Any element > 25:", np.any(arr > 25))  # True if any element satisfies
print("All elements > 25:", np.all(arr > 25))  # True if all elements satisfy


Any element > 25: True
All elements > 25: False


 **more advanced concepts** and techniques you can explore in NumPy to master its full potential:

---

### 22. **Structured Arrays**
Structured arrays allow you to store heterogeneous data (like rows in a database table).

```python
data = np.array([(1, 'Alice', 25), (2, 'Bob', 30)],
                dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])

print(data['name'])  # ['Alice' 'Bob']
print(data[data['age'] > 26])  # Filter rows where age > 26
```

---

### 23. **Fancy Indexing**
You can index with arrays of integers to reorder or extract elements.


In [4]:
array = np.array([10, 20, 30, 40, 50])
indices = [4, 0, 2]
print(array[indices])  # [50, 10, 30]

[50 10 30]


In [5]:

import numpy as np
data = np.array([(1, 'Alice', 25), (2, 'Bob', 30)],
                dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])

print(data['name'])  # ['Alice' 'Bob']
print(data[data['age'] > 26])  # Filter rows where age > 26
print(data.dtype)

['Alice' 'Bob']
[(2, 'Bob', 30)]
[('id', '<i4'), ('name', '<U10'), ('age', '<i4')]



You can also use it with 2D arrays:
```python
array = np.array([[1, 2], [3, 4], [5, 6]])
rows = [0, 1, 2]
cols = [1, 0, 1]
print(array[rows, cols])  # [2, 3, 6]
```

---

### 24. **Memory Management**
NumPy provides tools to handle memory usage efficiently.

#### Use `astype()` to save memory:
```python
array = np.array([1.0, 2.0, 3.0], dtype='float64')
array = array.astype('float32')  # Reduce precision to save memory
print(array.dtype)  # float32
```

#### Views vs Copies:
- **View**: A shallow copy pointing to the same data.
- **Copy**: A separate copy of the data.

```python
a = np.array([1, 2, 3])
b = a.view()  # View: changes to b affect a
b[0] = 100
print(a)  # [100 2 3]

c = a.copy()  # Copy: changes to c do not affect a
c[0] = 0
print(a)  # [100 2 3]
```

---

### 25. **NumPy and Pandas Integration**
NumPy arrays work seamlessly with **pandas** for data analysis.

```python
import pandas as pd

data = np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(data, columns=['Column1', 'Column2'])
print(df)
```

---

### 26. **Advanced Random Sampling**
You can generate more complex random samples.

```python
# Set a seed for reproducibility
np.random.seed(42)

# Random choice with probabilities
choices = np.random.choice([1, 2, 3], size=5, p=[0.2, 0.5, 0.3])
print(choices)  # Random, but with probabilities
```

---

In [6]:
a = np.array([1, 2, 3])
b = a.view()  # View: changes to b affect a
b[0] = 100
print(a)  # [100 2 3]

c = a.copy()  # Copy: changes to c do not affect a
c[0] = 0
print(a)  # [100 2 3]



d = a # this works same as view
d[0] = 3.14
print(a)

[100   2   3]
[100   2   3]
[3 2 3]


In [8]:
import pandas as pd

data = np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(data, columns=['Column1', 'Column2'])
print(df)
df = pd.DataFrame(data)
print(df)

   Column1  Column2
0        1        2
1        3        4
2        5        6
   0  1
0  1  2
1  3  4
2  5  6


In [11]:
# Set a seed for reproducibility
np.random.seed(42)

# Random choice with probabilities
choices = np.random.choice([1, 2, 3], size=5, p=[0.2, 0.5, 0.3])
print(choices)  # Random, but with probabilities


[2 3 3 2 1]



## OPtimization

### 27. **NumPy with Cython for Speed**
If you want faster code execution, you can use **Cython** to write C-optimized NumPy code.

Example with `%%cython` in Jupyter:
```cython
import numpy as np
cimport numpy as np

def add_arrays(np.ndarray[np.float64_t, ndim=1] a,
               np.ndarray[np.float64_t, ndim=1] b):
    cdef int n = a.shape[0]
    cdef np.ndarray[np.float64_t, ndim=1] c = np.empty(n)
    for i in range(n):
        c[i] = a[i] + b[i]
    return c
```

---

### 28. **NumPy with Multi-threading (Numba)**
You can use **Numba** to compile Python code into machine code and speed up NumPy operations.

```python
from numba import jit
import numpy as np

@jit(nopython=True)
def add_arrays(a, b):
    return a + b

a = np.arange(1e6)
b = np.arange(1e6)
result = add_arrays(a, b)
```

Numba is particularly useful for accelerating loops and numerical operations.

---

### 29. **Sparse Matrices**
If your data has many zeros, consider using **scipy.sparse** matrices for memory-efficient storage.

```python
from scipy import sparse

# Create a sparse matrix
dense = np.array([[0, 0, 1], [1, 0, 0]])
sparse_matrix = sparse.csr_matrix(dense)
print(sparse_matrix)

# Convert back to dense
print(sparse_matrix.toarray())
```

---

### 30. **Profiling NumPy Code**
You can profile the execution time of your NumPy code for optimization.

```python
import time
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
result = a + b
end = time.time()

print("Execution Time:", end - start)
```

---

This concludes some of the **most advanced NumPy concepts**. By mastering these, you'll be well-prepared for tasks in **data science**, **machine learning**, and **high-performance computing**.


In [12]:
!pip install cython

In [22]:
import numpy as np
cimport numpy as np

def add_arrays(np.ndarray[np.float64_t, ndim=1] a,
               np.ndarray[np.float64_t, ndim=1] b):
    cdef int n = a.shape[0]
    cdef np.ndarray[np.float64_t, ndim=1] c = np.empty(n, dtype=np.float64)
    for i in range(n):
        c[i] = a[i] + b[i]
    return c


SyntaxError: invalid syntax (<ipython-input-22-88f593696790>, line 2)

In [23]:
from scipy import sparse

# Create a sparse matrix
dense = np.array([[0, 0, 1], [1, 0, 0]])
sparse_matrix = sparse.csr_matrix(dense)
print(sparse_matrix)

# Convert back to dense
print(sparse_matrix.toarray())


  (0, 2)	1
  (1, 0)	1
[[0 0 1]
 [1 0 0]]


In [24]:
import time
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
result = a + b
end = time.time()

print("Execution Time:", end - start)


Execution Time: 0.010335683822631836


In [27]:
a = list(a)
b = list(b)
start = time.time()
result = [a[i] + b[i] for i in range(len(a))]
end = time.time()

print("Execution Time:", end - start)

Execution Time: 0.1810910701751709


In [ ]:
# Question : Create a 3×3 numpy array of all True’s

# Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)